baseurl = "https://freetrialbeforebuying.github.io/blog-2/"
title = "Hugo Themes"
themesDir = "themes"
publishDir = "docs"
theme = "hyde"
author = "Steve Francia"
copyright = "Copyright (c) 2008 - 2014, Steve Francia; all rights reserved."
canonifyurls = true
paginate = 3

[params]
    author = "John Doe"
    locale = "en-US"
